// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5mKprIKhdQFK1nLjHYFwW1eFUAlWA9Sw',
    appId: '1:943318599338:web:a9e591a04d009e302b72d3',
    messagingSenderId: '943318599338',
    projectId: 'nus-nus',
    authDomain: 'nus-nus.firebaseapp.com',
    storageBucket: 'nus-nus.firebasestorage.app',
    measurementId: 'G-3EMVG071P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBadfAj0AzMH5Lz1wwcwrzQZmuJCpFGJrw',
    appId: '1:943318599338:android:a7f4ae35917b5f712b72d3',
    messagingSenderId: '943318599338',
    projectId: 'nus-nus',
    storageBucket: 'nus-nus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZHKb91GtSmYBEDHsvDOL6dr1BiGRkGm4',
    appId: '1:943318599338:ios:20fc72f0dc4120592b72d3',
    messagingSenderId: '943318599338',
    projectId: 'nus-nus',
    storageBucket: 'nus-nus.firebasestorage.app',
    iosBundleId: 'com.example.nusNus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZHKb91GtSmYBEDHsvDOL6dr1BiGRkGm4',
    appId: '1:943318599338:ios:20fc72f0dc4120592b72d3',
    messagingSenderId: '943318599338',
    projectId: 'nus-nus',
    storageBucket: 'nus-nus.firebasestorage.app',
    iosBundleId: 'com.example.nusNus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5mKprIKhdQFK1nLjHYFwW1eFUAlWA9Sw',
    appId: '1:943318599338:web:6dba3e9f716e25ca2b72d3',
    messagingSenderId: '943318599338',
    projectId: 'nus-nus',
    authDomain: 'nus-nus.firebaseapp.com',
    storageBucket: 'nus-nus.firebasestorage.app',
    measurementId: 'G-0LGHQVZR3F',
  );
}
